backend:
  name: git-gateway
  branch: main
  commit_messages:
    create: 'content: create {{collection}} “{{slug}}”'
    update: 'content: update {{collection}} “{{slug}}”'
    delete: 'content: delete {{collection}} “{{slug}}”'
    uploadMedia: 'content: upload “{{path}}”'
    deleteMedia: 'content: delete “{{path}}”'

media_folder: 'src/content/images'
public_folder: '../images'

collections:
  - name: 'pages'
    label: 'Pages'
    files:
      - file: 'src/content/markdown/index.md'
        label: 'Landing Page'
        name: 'index'
        fields:
          - {
              label: 'Title',
              name: title,
              widget: string,
              default: 'Francesca Giacco',
              hint: 'This title will be used in the page metadata only.',
            }
          - {
              label: 'Meta Description',
              name: meta_description,
              widget: text,
              default: 'Francesca Giacco',
              hint: 'This description will be used in the page metadata only.',
            }
          - { label: 'Book Cover Image', name: book_cover_image, widget: image }
          - {
              label: 'Book Cover Alt Text',
              name: book_cover_alt_text,
              widget: string,
              hint: "The book cover image's alt text will be used as the primary heading of the landing page for screen readers.",
            }
          - { label: 'Book Pitch', name: book_pitch, widget: markdown }
          - {
              label: 'Book Description',
              name: book_description,
              widget: markdown,
            }
          - { label: 'Buy Heading', name: buy_heading, widget: string }
          - {
              label: 'Buy Button',
              name: buy_button,
              widget: list,
              allow_add: true,
              min: 1,
              max: 3,
              fields:
                [
                  { label: 'Vendor Name', name: vendor_name, widget: string },
                  { label: 'Vendor Link', name: vendor_link, widget: string },
                ],
            }
          - {
              label: Praise,
              name: praise,
              widget: list,
              allow_add: true,
              fields:
                [
                  { label: 'Quote', name: quote, widget: markdown },
                  { label: Attribution, name: attribution, widget: markdown },
                ],
            }
          - { label: 'Author Photo', name: author_photo, widget: image }
          - {
              label: 'Author Photo Alt text',
              name: author_photo_alt_text,
              widget: string,
            }
          - {
              label: 'Mini About the Author',
              name: mini_about,
              widget: markdown,
            }
      - file: 'src/content/markdown/about.md'
        label: 'About Page'
        name: 'about'
        fields:
          - {
              label: 'Title',
              name: title,
              widget: string,
              default: 'About | Francesca Giacco',
              hint: 'This title will be used in the page metadata only.',
            }
          - {
              label: 'Meta Description',
              name: meta_description,
              widget: text,
              hint: 'This description will be used in the page metadata only.',
            }
          - { label: 'Page Heading', name: page_heading, widget: string }
          - { label: 'Author Photo', name: author_photo, widget: image }
          - {
              label: 'Author Photo Alt Text',
              name: author_photo_alt_text,
              widget: string,
            }
          - { label: 'About the Author', name: about, widget: markdown }
