backend:
  name: git-gateway
  branch: main
  commit_messages:
    create: 'content: create {{collection}} “{{slug}}”'
    update: 'content: update {{collection}} “{{slug}}”'
    delete: 'content: delete {{collection}} “{{slug}}”'
    uploadMedia: 'content: upload “{{path}}”'
    deleteMedia: 'content: delete “{{path}}”'

media_folder: 'static/images'
public_folder: '/images'

collections:
  - name: 'pages'
    label: 'Pages'
    files:
      - file: 'src/pages/index.md'
        label: 'Landing Page'
        name: 'index'
        fields:
          - { label: 'Book Cover Image', name: bookcoverimage, widget: image }
          - {
              label: 'Book Cover Alt Text',
              name: bookcoveralttext,
              widget: string,
              hint: "NOTE: The book cover image's alt text will be used as the primary heading of the landing page for screen readers and search engines.",
            }
          - { label: 'Book Pitch', name: bookpitch, widget: markdown }
          - {
              label: 'Book Description',
              name: bookdescription,
              widget: markdown,
            }
          - { label: 'Buy Heading', name: buyheading, widget: string }
          - {
              label: 'Buy Button',
              name: buybutton,
              widget: list,
              allow_add: true,
              min: 1,
              max: 3,
              fields:
                [
                  { label: 'Vendor Name', name: vendorname, widget: text },
                  { label: 'Vendor Link', name: vendorlink, widget: text },
                ],
            }
          - {
              label: Praise,
              name: praise,
              widget: list,
              allow_add: true,
              fields:
                [
                  { label: 'Quote', name: quote, widget: markdown },
                  { label: Attribution, name: attribution, widget: markdown },
                ],
            }
          - { label: 'Author Photo', name: authorphoto, widget: image }
          - {
              label: 'Author Photo Alt text',
              name: authorphotoalttext,
              widget: string,
            }
          - {
              label: 'Mini About the Author',
              name: miniabout,
              widget: markdown,
            }
