backend:
  name: git-gateway
  branch: main
  commit_messages:
    create: "content: create {{collection}} “{{slug}}”"
    update: "content: update {{collection}} “{{slug}}”"
    delete: "content: delete {{collection}} “{{slug}}”"
    uploadMedia: "content: upload “{{path}}”"
    deleteMedia: "content: delete “{{path}}”"

  publish_mode: editorial_workflow

  media_folder: "static/images"
  public_folder: "/images"

  

