backend:
  name: git-gateway
  branch: main
  commit_messages:
    create: 'content: create {{collection}} “{{slug}}”'
    update: 'content: update {{collection}} “{{slug}}”'
    delete: 'content: delete {{collection}} “{{slug}}”'
    uploadMedia: 'content: upload “{{path}}”'
    deleteMedia: 'content: delete “{{path}}”'

media_folder: 'static/images'
public_folder: '/images'

collections:
  - name: 'pages'
    label: 'Pages'
    files:
      - file: 'src/pages/index.md'
        label: 'Landing Page'
        name: 'index'
        fields:
          - {
              label: 'Book Pitch',
              name: bookpitch,
              widget: object,
              fields:
                [
                  {
                    label: 'Book Cover Image',
                    name: bookcoverimage,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        {
                          label: Alt,
                          name: alt,
                          widget: string,
                          hint: "NOTE: The book cover image's alt text will be used as the primary heading of the landing page for screen readers and search engines.",
                        },
                      ],
                  },
                  { label: 'Blurb', name: blurb, widget: text },
                  { label: 'Description', name: description, widget: text },
                ],
            }
          - {
              label: 'Buy CTA',
              name: buycta,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  {
                    label: 'Buy Buttons',
                    name: buybuttons,
                    widget: list,
                    allow_add: true,
                    min: 1,
                    max: 3,
                    fields:
                      [
                        {
                          label: 'Vendor Name',
                          name: vendorname,
                          widget: text,
                        },
                        {
                          label: 'Vendor Link',
                          name: vendorlink,
                          widget: text,
                        },
                      ],
                  },
                ],
            }
          - {
              label: Praise,
              name: praise,
              widget: list,
              allow_add: true,
              fields:
                [
                  { label: 'Quote', name: quote, widget: text },
                  { label: Attribution, name: attribution, widget: text },
                ],
            }
          - {
              label: 'Mini About the Author',
              name: miniabout,
              widget: object,
              fields:
                [
                  {
                    label: 'Author Photo',
                    name: authorphoto,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Alt, name: alt, widget: string },
                      ],
                  },
                  { label: 'Mini About', name: miniabout, widget: markdown },
                ],
            }
